name: pull_request

on: [pull_request]

jobs:
  code_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '18']

    steps:
      - name: ğŸ— Setup Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ— Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.x

      - name: ğŸ— Setup cache ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: ğŸ“¦ Install
        run: pnpm install --frozen-lockfile

      - name: ğŸš¨ Lint
        run: pnpm lint

      - name: ğŸ¨ Format
        run: pnpm format

      - name: ğŸ·ï¸ Type Check
        run: pnpm ts

      - name: âœ… Test
        run: pnpm test:coverage

      - name: âœ… Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/coverage-final.json

      - name: ğŸ”§ Build
        run: pnpm build

  commit_check:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ— Setup Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸš¨ Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml

  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ— Setup Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸš¨ Spellcheck
        uses: streetsidesoftware/cspell-action@v2.12.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          inline: error
